package cmake

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/snowmerak/aloy/internal/model"
	"github.com/snowmerak/aloy/internal/parser"
	"github.com/snowmerak/aloy/internal/resolver"
)

// GenerateMaster creates the root CMakeLists.txt for the project.
func GenerateMaster(projectRoot string, cfg *model.ProjectConfig, resolvedDeps []resolver.ResolvedDep) error {
	var b strings.Builder

	writeHeader(&b, cfg)
	writeDependencies(&b, cfg, resolvedDeps, projectRoot)
	if err := writeTargets(&b, cfg, projectRoot); err != nil {
		return err
	}
	writeInjectCMake(&b, cfg)

	path := filepath.Join(projectRoot, "CMakeLists.txt")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

// GenerateForModule creates a CMakeLists.txt for an aloy sub-package in .my_modules/.
func GenerateForModule(modulePath string) error {
	cfg, err := parser.LoadProject(modulePath)
	if err != nil {
		return fmt.Errorf("failed to load module project.yaml: %w", err)
	}

	var b strings.Builder

	fmt.Fprintf(&b, "# Auto-generated by aloy — DO NOT EDIT\n")
	fmt.Fprintf(&b, "cmake_minimum_required(VERSION 3.15)\n")
	fmt.Fprintf(&b, "project(%s)\n\n", sanitizeCMakeName(cfg.Project.Name))

	if cfg.Project.CXXStandard > 0 {
		fmt.Fprintf(&b, "set(CMAKE_CXX_STANDARD %d)\n", cfg.Project.CXXStandard)
		b.WriteString("set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n")
	}

	// Write targets for this module
	for targetName, target := range cfg.Targets {
		cmakeName := sanitizeCMakeName(targetName)
		sources, err := ScanSources(target.Sources, modulePath)
		if err != nil {
			return fmt.Errorf("failed to scan sources for target %s: %w", targetName, err)
		}
		if err := writeTargetBlock(&b, cmakeName, &target, sources, modulePath); err != nil {
			return fmt.Errorf("failed to write target %s: %w", targetName, err)
		}
	}

	path := filepath.Join(modulePath, "CMakeLists.txt")
	return os.WriteFile(path, []byte(b.String()), 0644)
}

func writeHeader(b *strings.Builder, cfg *model.ProjectConfig) {
	fmt.Fprintf(b, "# Auto-generated by aloy — DO NOT EDIT\n")
	fmt.Fprintf(b, "cmake_minimum_required(VERSION 3.15)\n")
	fmt.Fprintf(b, "project(%s VERSION %s)\n\n",
		sanitizeCMakeName(cfg.Project.Name), cfg.Project.Version)

	if cfg.Project.CXXStandard > 0 {
		fmt.Fprintf(b, "set(CMAKE_CXX_STANDARD %d)\n", cfg.Project.CXXStandard)
		b.WriteString("set(CMAKE_CXX_STANDARD_REQUIRED ON)\n\n")
	}

	hasTest := false
	for _, target := range cfg.Targets {
		if target.Type == "test" {
			hasTest = true
			break
		}
	}
	if hasTest {
		b.WriteString("enable_testing()\n\n")
	}
}

func writeDependencies(b *strings.Builder, cfg *model.ProjectConfig, resolvedDeps []resolver.ResolvedDep, projectRoot string) {
	// Build a lookup for resolved deps
	depMap := make(map[string]*resolver.ResolvedDep)
	for i := range resolvedDeps {
		depMap[resolvedDeps[i].LogicalName] = &resolvedDeps[i]
	}

	// Collect all unique dependencies across targets
	seen := make(map[string]bool)
	var allDeps []model.Dependency
	for _, target := range cfg.Targets {
		for _, dep := range target.Dependencies {
			key := dep.ModuleDir()
			if !seen[key] {
				seen[key] = true
				allDeps = append(allDeps, dep)
			}
		}
	}

	// System packages: find_package
	for _, dep := range allDeps {
		if dep.Type == "system" {
			fmt.Fprintf(b, "find_package(%s REQUIRED)\n", dep.Name)
		}
	}

	// Git packages: cmake_options + add_subdirectory OR imported target (meson)
	for _, dep := range allDeps {
		if dep.Type == "system" {
			continue
		}
		logicalName := dep.ModuleDir()
		rd := depMap[logicalName]
		if rd == nil {
			continue
		}

		targetName := dep.TargetName()
		if dep.CMakeTarget != "" {
			targetName = dep.CMakeTarget
		}

		if rd.Type == "custom" {
			repoPath := filepath.Join(projectRoot, resolver.ModulesDir, rd.RepoDir, rd.Subdir)

			var includeCMakePath string
			if len(rd.IncludeDirs) > 0 {
				var includeCMakePaths []string
				for _, inc := range rd.IncludeDirs {
					relIncPath := filepath.Join(resolver.ModulesDir, rd.RepoDir, rd.Subdir, inc)
					includeCMakePaths = append(includeCMakePaths, "${CMAKE_CURRENT_SOURCE_DIR}/"+filepath.ToSlash(relIncPath))
				}
				includeCMakePath = strings.Join(includeCMakePaths, ";")
			} else {
				includeSub := findHeaderIncludeDir(repoPath)
				includeRelPath := filepath.Join(resolver.ModulesDir, rd.RepoDir, rd.Subdir, includeSub)
				includeCMakePath = "${CMAKE_CURRENT_SOURCE_DIR}/" + filepath.ToSlash(includeRelPath)
			}

			relativeDirs := rd.LibDirs
			if len(relativeDirs) == 0 {
				relativeDirs = []string{".", "lib", "build", "bin"}
			}
			libPaths, err := findLibraryFilesDirs(repoPath, relativeDirs)

			if err != nil {
				fmt.Fprintf(b, "add_library(%s INTERFACE IMPORTED)\n", targetName)
				fmt.Fprintf(b, "set_target_properties(%s PROPERTIES\n", targetName)
				fmt.Fprintf(b, "    INTERFACE_INCLUDE_DIRECTORIES %q\n", includeCMakePath)
				fmt.Fprintf(b, ")\n")
			} else {
				var cmakeLibPaths []string
				for _, p := range libPaths {
					relLibPath, relErr := filepath.Rel(projectRoot, p)
					if relErr != nil {
						relLibPath = p
					}
					cmakeLibPaths = append(cmakeLibPaths, "${CMAKE_CURRENT_SOURCE_DIR}/"+filepath.ToSlash(relLibPath))
				}
				joinedLibs := strings.Join(cmakeLibPaths, ";")

				fmt.Fprintf(b, "add_library(%s INTERFACE IMPORTED)\n", targetName)
				fmt.Fprintf(b, "set_target_properties(%s PROPERTIES\n", targetName)
				fmt.Fprintf(b, "    INTERFACE_LINK_LIBRARIES %q\n", joinedLibs)
				fmt.Fprintf(b, "    INTERFACE_INCLUDE_DIRECTORIES %q\n", includeCMakePath)
				fmt.Fprintf(b, ")\n")
			}
			continue
		}

		if rd.Type == "header_only" {
			repoPath := filepath.Join(projectRoot, resolver.ModulesDir, rd.RepoDir, rd.Subdir)
			includeSub := findHeaderIncludeDir(repoPath)
			includeRelPath := filepath.Join(resolver.ModulesDir, rd.RepoDir, rd.Subdir, includeSub)
			includeCMakePath := filepath.ToSlash(includeRelPath)

			fmt.Fprintf(b, "add_library(%s INTERFACE IMPORTED)\n", targetName)
			fmt.Fprintf(b, "set_target_properties(%s PROPERTIES\n", targetName)
			fmt.Fprintf(b, "    INTERFACE_INCLUDE_DIRECTORIES \"${CMAKE_CURRENT_SOURCE_DIR}/%s\"\n", includeCMakePath)
			fmt.Fprintf(b, ")\n")
			continue
		}

		if rd.Type == "meson" {
			installDir := filepath.Join(projectRoot, resolver.ModulesDir, rd.LogicalName+"_install")
			libPaths, err := findLibraryFiles(installDir)

			includeDir := filepath.Join(installDir, "include")
			includeRelPath := filepath.Join(resolver.ModulesDir, rd.LogicalName+"_install", "include")
			if _, errStat := os.Stat(includeDir); errStat != nil {
				includeRelPath = filepath.Join(resolver.ModulesDir, rd.RepoDir, rd.Subdir)
			}
			includeCMakePath := filepath.ToSlash(includeRelPath)

			if err != nil {
				fmt.Fprintf(b, "add_library(%s INTERFACE IMPORTED)\n", targetName)
				fmt.Fprintf(b, "set_target_properties(%s PROPERTIES\n", targetName)
				fmt.Fprintf(b, "    INTERFACE_INCLUDE_DIRECTORIES \"${CMAKE_CURRENT_SOURCE_DIR}/%s\"\n", includeCMakePath)
				fmt.Fprintf(b, ")\n")
			} else {
				var cmakeLibPaths []string
				for _, p := range libPaths {
					relLibPath, relErr := filepath.Rel(projectRoot, p)
					if relErr != nil {
						relLibPath = p
					}
					cmakeLibPaths = append(cmakeLibPaths, "${CMAKE_CURRENT_SOURCE_DIR}/"+filepath.ToSlash(relLibPath))
				}
				joinedLibs := strings.Join(cmakeLibPaths, ";")

				fmt.Fprintf(b, "add_library(%s INTERFACE IMPORTED)\n", targetName)
				fmt.Fprintf(b, "set_target_properties(%s PROPERTIES\n", targetName)
				fmt.Fprintf(b, "    INTERFACE_LINK_LIBRARIES %q\n", joinedLibs)
				fmt.Fprintf(b, "    INTERFACE_INCLUDE_DIRECTORIES \"${CMAKE_CURRENT_SOURCE_DIR}/%s\"\n", includeCMakePath)
				fmt.Fprintf(b, ")\n")
			}
			continue
		}

		// Inject cmake_options as cache variables
		for k, v := range dep.CMakeOptions {
			cacheType := "STRING"
			upper := strings.ToUpper(v)
			if upper == "ON" || upper == "OFF" || upper == "TRUE" || upper == "FALSE" {
				cacheType = "BOOL"
			}
			fmt.Fprintf(b, "set(%s %q CACHE %s \"\" FORCE)\n", k, v, cacheType)
		}

		sourcePath := filepath.ToSlash(filepath.Join(resolver.ModulesDir, rd.RepoDir, rd.Subdir))
		binaryPath := filepath.ToSlash(filepath.Join(resolver.ModulesDir, rd.LogicalName))
		// We use sourcePath and binaryPath to allow multiple subdirectories from the same repo
		fmt.Fprintf(b, "add_subdirectory(%s %s)\n", sourcePath, binaryPath)
	}

	if len(allDeps) > 0 {
		b.WriteString("\n")
	}
}

func findLibraryFiles(installDir string) ([]string, error) {
	libDirs := []string{
		filepath.Join(installDir, "lib"),
		filepath.Join(installDir, "lib64"),
		filepath.Join(installDir, "bin"),
	}

	var candidates []string
	for _, dir := range libDirs {
		files, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, file := range files {
			if file.IsDir() {
				continue
			}
			ext := filepath.Ext(file.Name())
			if ext == ".a" || ext == ".lib" || ext == ".so" || ext == ".dylib" {
				candidates = append(candidates, filepath.Join(dir, file.Name()))
			}
		}
	}

	if len(candidates) == 0 {
		return nil, fmt.Errorf("no library file found in install directory %s", installDir)
	}

	return candidates, nil
}

func findHeaderIncludeDir(repoPath string) string {
	candidates := []string{"single_include", "include", "includes", "src"}
	for _, c := range candidates {
		path := filepath.Join(repoPath, c)
		if info, err := os.Stat(path); err == nil && info.IsDir() {
			return c
		}
	}
	return ""
}

func findLibraryFilesDirs(repoPath string, relativeDirs []string) ([]string, error) {
	var candidates []string
	for _, relDir := range relativeDirs {
		dir := filepath.Join(repoPath, relDir)
		files, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, file := range files {
			if file.IsDir() {
				continue
			}
			ext := filepath.Ext(file.Name())
			if ext == ".a" || ext == ".lib" || ext == ".so" || ext == ".dylib" {
				candidates = append(candidates, filepath.Join(dir, file.Name()))
			}
		}
	}

	if len(candidates) == 0 {
		return nil, fmt.Errorf("no library file found in custom lib directories %v inside %s", relativeDirs, repoPath)
	}

	return candidates, nil
}

func writeTargets(b *strings.Builder, cfg *model.ProjectConfig, projectRoot string) error {
	for targetName, target := range cfg.Targets {
		cmakeName := sanitizeCMakeName(targetName)

		// Scan source files (hardcoded, no GLOB)
		sources, err := ScanSources(target.Sources, projectRoot)
		if err != nil {
			return fmt.Errorf("failed to scan sources for target %s: %w", targetName, err)
		}

		if err := writeTargetBlock(b, cmakeName, &target, sources, projectRoot); err != nil {
			return fmt.Errorf("failed to write target %s: %w", targetName, err)
		}
		b.WriteString("\n")
	}
	return nil
}

func writeTargetBlock(b *strings.Builder, cmakeName string, target *model.Target, sources []string, projectRoot string) error {
	// Add target
	switch target.Type {
	case "executable", "test":
		fmt.Fprintf(b, "add_executable(%s)\n", cmakeName)
	case "library":
		fmt.Fprintf(b, "add_library(%s STATIC)\n", cmakeName)
	case "shared_library":
		fmt.Fprintf(b, "add_library(%s SHARED)\n", cmakeName)
	case "header_only":
		fmt.Fprintf(b, "add_library(%s INTERFACE)\n", cmakeName)
	default:
		fmt.Fprintf(b, "add_executable(%s)\n", cmakeName)
	}

	// Sources (not for header_only)
	if target.Type != "header_only" && len(sources) > 0 {
		fmt.Fprintf(b, "target_sources(%s PRIVATE\n", cmakeName)
		for _, s := range sources {
			fmt.Fprintf(b, "    %s\n", s)
		}
		b.WriteString(")\n")
	}

	// Include directories
	if len(target.Includes.Public) > 0 {
		keyword := "PUBLIC"
		if target.Type == "header_only" {
			keyword = "INTERFACE"
		}
		fmt.Fprintf(b, "target_include_directories(%s %s\n", cmakeName, keyword)
		for _, inc := range target.Includes.Public {
			fmt.Fprintf(b, "    %s\n", inc)
		}
		b.WriteString(")\n")
	}
	if len(target.Includes.Private) > 0 && target.Type != "header_only" {
		fmt.Fprintf(b, "target_include_directories(%s PRIVATE\n", cmakeName)
		for _, inc := range target.Includes.Private {
			fmt.Fprintf(b, "    %s\n", inc)
		}
		b.WriteString(")\n")
	}

	// Link dependencies
	if len(target.Dependencies) > 0 {
		keyword := "PRIVATE"
		if target.Type == "header_only" {
			keyword = "INTERFACE"
		}
		fmt.Fprintf(b, "target_link_libraries(%s %s\n", cmakeName, keyword)
		for _, dep := range target.Dependencies {
			var linkName string
			if dep.Type == "system" {
				linkName = dep.Name
			} else if dep.CMakeTarget != "" {
				linkName = dep.CMakeTarget
			} else {
				linkName = dep.TargetName()
			}
			fmt.Fprintf(b, "    %s\n", linkName)
		}
		b.WriteString(")\n")
	}

	// Platform-specific blocks
	for platform, pcfg := range target.Platforms {
		cond := platformCondition(platform)
		if cond == "" {
			continue
		}

		fmt.Fprintf(b, "if(%s)\n", cond)

		if len(pcfg.Sources) > 0 && target.Type != "header_only" {
			platSources, err := ScanSources(pcfg.Sources, projectRoot)
			if err != nil {
				return fmt.Errorf("failed to scan platform %s sources: %w", platform, err)
			}
			fmt.Fprintf(b, "    target_sources(%s PRIVATE\n", cmakeName)
			for _, s := range platSources {
				fmt.Fprintf(b, "        %s\n", s)
			}
			b.WriteString("    )\n")
		}

		if len(pcfg.CompilerFlags) > 0 {
			keyword := "PRIVATE"
			if target.Type == "header_only" {
				keyword = "INTERFACE"
			}
			fmt.Fprintf(b, "    target_compile_options(%s %s %s)\n",
				cmakeName, keyword, strings.Join(pcfg.CompilerFlags, " "))
		}

		if len(pcfg.LinkerFlags) > 0 && target.Type != "header_only" {
			fmt.Fprintf(b, "    target_link_options(%s PRIVATE %s)\n",
				cmakeName, strings.Join(pcfg.LinkerFlags, " "))
		}

		b.WriteString("endif()\n")
	}

	if target.Pch != "" {
		keyword := "PRIVATE"
		if target.Type == "header_only" {
			keyword = "INTERFACE"
		}
		fmt.Fprintf(b, "    target_precompile_headers(%s %s %s)\n", cmakeName, keyword, target.Pch)
	}

	if target.Type == "test" {
		fmt.Fprintf(b, "    add_test(NAME %s COMMAND %s)\n", cmakeName, cmakeName)
	}

	return nil
}

func writeInjectCMake(b *strings.Builder, cfg *model.ProjectConfig) {
	if cfg.InjectCMake != "" {
		fmt.Fprintf(b, "\ninclude(%s)\n", cfg.InjectCMake)
	}
}

func platformCondition(name string) string {
	switch strings.ToLower(name) {
	case "windows", "win", "win32":
		return "WIN32"
	case "linux":
		return "UNIX AND NOT APPLE"
	case "macos", "macosx", "darwin", "apple":
		return "APPLE"
	case "unix":
		return "UNIX"
	default:
		return ""
	}
}

func sanitizeCMakeName(name string) string {
	var b strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	s := b.String()
	if s == "" {
		return "unnamed"
	}
	// CMake names cannot start with a digit
	if s[0] >= '0' && s[0] <= '9' {
		s = "_" + s
	}
	return s
}
